# Generated by Django 5.1.6 on 2025-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('symbol', models.CharField(max_length=50)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_traded_quantity', models.BigIntegerField(blank=True, null=True)),
                ('total_traded_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('last_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('average_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
