# Generated by Django 5.1.6 on 2025-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_alter_stockdata_average_traded_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='total_trades',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
