# Generated by Django 5.1.6 on 2025-03-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_alter_stockdata_total_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=100)),
                ('contract_no', models.CharField(max_length=100)),
                ('stock_symbol', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
