# Generated by Django 5.1.6 on 2025-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_stocktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_symbol',
            field=models.CharField(max_length=50),
        ),
    ]
