# Generated by Django 5.1.6 on 2025-03-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_delete_daywiselivedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.PositiveIntegerField(unique=True)),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
