# Generated by Django 5.1.6 on 2025-03-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_brokervolume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerVolume',
        ),
    ]
