# Generated by Django 5.1.6 on 2025-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_volume', models.FloatField()),
                ('time_period', models.CharField(default='latest_date', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FloorsheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('buyer', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockwiseBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('broker_id', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('percent_volume', models.FloatField()),
                ('date_range', models.CharField(max_length=50)),
                ('time_frame', models.CharField(max_length=20)),
            ],
        ),
    ]
