# Generated by Django 5.1.6 on 2025-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkVolumeTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=255)),
                ('buy_broker', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('time_frame', models.CharField(max_length=20)),
                ('date_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WashTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('date_range', models.CharField(max_length=50)),
                ('time_frame', models.CharField(max_length=20)),
                ('buyer_seller', models.CharField(max_length=255)),
            ],
        ),
    ]
