# Generated by Django 5.1.6 on 2025-03-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_bulkvolumetrade_washtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigPlayerAccumulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('buying_broker', models.CharField(max_length=255)),
                ('selling_brokers', models.TextField()),
                ('time_frame', models.CharField(max_length=20)),
                ('date_range', models.CharField(max_length=50)),
            ],
        ),
    ]
