# Generated by Django 5.1.6 on 2025-03-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0004_alter_bigplayeraccumulation_buying_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorsheetdata',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
