# Generated by Django 5.1.6 on 2025-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0005_floorsheetdata_transaction_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigPlayerDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('buying_broker', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_brokers', models.TextField(blank=True, null=True)),
                ('time_frame', models.CharField(blank=True, max_length=20, null=True)),
                ('date_range', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
