# Generated by Django 5.1.6 on 2025-03-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0006_bigplayerdistribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bigplayerdistribution',
            old_name='buying_broker',
            new_name='buying_brokers',
        ),
        migrations.RenameField(
            model_name='bigplayerdistribution',
            old_name='selling_brokers',
            new_name='selling_broker',
        ),
    ]
