# Generated by Django 5.1.6 on 2025-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0007_rename_buying_broker_bigplayerdistribution_buying_brokers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigplayerdistribution',
            name='buying_brokers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bigplayerdistribution',
            name='selling_broker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
