# Generated by Django 5.1.6 on 2025-03-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0010_remove_brokerwiseaccumulation_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokerwiseaccumulation',
            old_name='quantity',
            new_name='buying_quantity',
        ),
    ]
