# Generated by Django 5.1.6 on 2025-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0014_pingpongtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingpongtrade',
            name='max_time_diff',
            field=models.FloatField(help_text='Maximum time difference between trades (minutes)', null=True),
        ),
        migrations.AddField(
            model_name='pingpongtrade',
            name='min_time_diff',
            field=models.FloatField(help_text='Minimum time difference between trades (minutes)', null=True),
        ),
    ]
