# Generated by Django 5.1.6 on 2025-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0015_pingpongtrade_max_time_diff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPriceDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('transaction_count', models.IntegerField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('price_change', models.FloatField()),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('is_investigated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Flat Price Detections',
                'ordering': ['-detection_date'],
            },
        ),
    ]
