# Generated by Django 5.1.6 on 2025-03-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0016_flatpricedetection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatPriceDetection',
        ),
    ]
