# Generated by Django 5.1.6 on 2025-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0018_flatpricedetection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpricedetection',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='flatpricedetection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flatpricedetection',
            name='price_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatpricedetection',
            name='transactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flatpricedetection',
            name='date_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flatpricedetection',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='avg_rate',
        ),
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='flat_transactions',
        ),
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='max_rate',
        ),
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='min_rate',
        ),
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='price_change_percentage',
        ),
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='total_transactions',
        ),
    ]
