# Generated by Django 5.1.6 on 2025-03-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0019_alter_flatpricedetection_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatpricedetection',
            old_name='transactions',
            new_name='total_transactions',
        ),
    ]
