# Generated by Django 5.1.6 on 2025-03-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0020_rename_transactions_flatpricedetection_total_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='date_range',
        ),
        migrations.AddField(
            model_name='flatpricedetection',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
