# Generated by Django 5.1.6 on 2025-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0021_remove_flatpricedetection_date_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatpricedetection',
            name='date',
        ),
        migrations.AddField(
            model_name='flatpricedetection',
            name='date_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
