# Generated by Django 5.1.6 on 2025-03-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0024_alter_wallbreaktracking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WallBreakTracking',
        ),
    ]
