# Generated by Django 5.1.6 on 2025-03-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0028_accumulationdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccumulationData',
        ),
    ]
