# Generated by Django 5.1.6 on 2025-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0030_accumulationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('seller_broker', models.CharField(blank=True, max_length=100, null=True)),
                ('signal', models.CharField(blank=True, max_length=200, null=True)),
                ('analysis_type', models.CharField(choices=[('DAILY_SUMMARY', 'Daily Summary'), ('DISTRIBUTION_SIGNAL', 'Distribution Signal'), ('LARGE_SELLER', 'Large Seller')], max_length=20)),
            ],
            options={
                'verbose_name': 'Distribution Analysis',
                'verbose_name_plural': 'Distribution Analyses',
                'indexes': [models.Index(fields=['symbol'], name='data_analys_symbol_6f9d8e_idx'), models.Index(fields=['timestamp'], name='data_analys_timesta_d53d28_idx'), models.Index(fields=['analysis_type'], name='data_analys_analysi_46e68d_idx')],
            },
        ),
    ]
