# Generated by Django 5.1.6 on 2025-03-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0033_distributionanalysis_largesellers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistributionAnalysis',
        ),
        migrations.DeleteModel(
            name='LargeSellers',
        ),
    ]
