# Generated by Django 5.1.6 on 2025-03-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0034_delete_distributionanalysis_delete_largesellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('is_large_trade', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'distribution_data',
            },
        ),
    ]
