# Generated by Django 5.1.6 on 2025-03-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0035_distributiondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistributionData',
        ),
    ]
