# Generated by Django 5.1.6 on 2025-03-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0038_delete_distributionanalysis_delete_largesellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distribution_analysis',
            },
        ),
        migrations.CreateModel(
            name='LargeSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'large_sellers',
            },
        ),
    ]
