# Generated by Django 5.1.6 on 2025-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0039_distributionanalysis_largesellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlliquidStockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_transactions', models.IntegerField(blank=True, null=True)),
                ('volume_percent', models.FloatField(blank=True, null=True)),
                ('buying_broker', models.CharField(blank=True, max_length=255, null=True)),
                ('selling_broker', models.CharField(blank=True, max_length=255, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('script', 'analysis_date')},
            },
        ),
    ]
