# Generated by Django 5.1.6 on 2025-03-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0040_illiquidstockreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IlliquidStockReport',
        ),
    ]
