# Generated by Django 5.1.6 on 2025-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0046_delete_funownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_id', models.CharField(max_length=20)),
                ('updated_on', models.DateField()),
                ('promoter_shares', models.BigIntegerField()),
                ('public_shares', models.BigIntegerField()),
                ('total_listed_shares', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'FUN Ownership',
                'verbose_name_plural': 'FUN Ownership Data',
                'ordering': ['-updated_on', 'symbol'],
                'unique_together': {('script_id', 'updated_on')},
            },
        ),
    ]
