# Generated by Django 5.1.6 on 2025-03-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0049_funownership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunOwnership',
        ),
    ]
