# Generated by Django 5.1.6 on 2025-03-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0054_volumetradereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolumeTradeReport',
        ),
    ]
