# Generated by Django 5.1.6 on 2025-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0055_delete_volumetradereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeTradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_frame', models.CharField(blank=True, max_length=10, null=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('public_share', models.BigIntegerField(blank=True, null=True)),
                ('trading_volume', models.BigIntegerField(blank=True, null=True)),
                ('traded_volume_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report_date', models.DateField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volume Trade Report',
                'verbose_name_plural': 'Volume Trade Reports',
                'ordering': ['time_frame', 'symbol'],
                'indexes': [models.Index(fields=['time_frame', 'symbol'], name='data_analys_time_fr_d9dc0e_idx')],
            },
        ),
    ]
