# Generated by Django 5.1.6 on 2025-03-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0056_volumetradereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumetradereport',
            name='created_at',
        ),
    ]
