# Generated by Django 5.1.6 on 2025-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0057_remove_volumetradereport_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('streak_type', models.CharField(blank=True, choices=[('buying', 'Buying Streak'), ('selling', 'Selling Streak')], max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('streak_length', models.PositiveIntegerField(blank=True, null=True)),
                ('total_quantity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Broker Streak',
                'verbose_name_plural': 'Broker Streaks',
                'ordering': ['-streak_length', 'symbol', 'broker'],
                'indexes': [models.Index(fields=['symbol'], name='data_analys_symbol_ded2c2_idx'), models.Index(fields=['broker'], name='data_analys_broker_c34b52_idx'), models.Index(fields=['streak_type'], name='data_analys_streak__d3e200_idx'), models.Index(fields=['start_date', 'end_date'], name='data_analys_start_d_551ec8_idx')],
            },
        ),
    ]
