# Generated by Django 5.1.6 on 2025-03-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0058_brokerstreak'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrokerStreak',
            new_name='ConsecutiveStreak',
        ),
        migrations.RenameIndex(
            model_name='consecutivestreak',
            new_name='data_analys_symbol_28a539_idx',
            old_name='data_analys_symbol_ded2c2_idx',
        ),
        migrations.RenameIndex(
            model_name='consecutivestreak',
            new_name='data_analys_broker_3e1341_idx',
            old_name='data_analys_broker_c34b52_idx',
        ),
        migrations.RenameIndex(
            model_name='consecutivestreak',
            new_name='data_analys_streak__634397_idx',
            old_name='data_analys_streak__d3e200_idx',
        ),
        migrations.RenameIndex(
            model_name='consecutivestreak',
            new_name='data_analys_start_d_84ea75_idx',
            old_name='data_analys_start_d_551ec8_idx',
        ),
    ]
