# Generated by Django 5.1.6 on 2025-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0059_rename_brokerstreak_consecutivestreak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('movement_type', models.CharField(blank=True, choices=[('jump', 'Price Jump'), ('fall', 'Price Fall')], max_length=4, null=True)),
                ('percentage_change', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
                'indexes': [models.Index(fields=['symbol'], name='data_analys_symbol_ebd7f1_idx'), models.Index(fields=['date'], name='data_analys_date_b5e032_idx'), models.Index(fields=['movement_type'], name='data_analys_movemen_1fe20c_idx')],
            },
        ),
    ]
