# Generated by Django 5.1.6 on 2025-03-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0060_pricemovement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceMovement',
        ),
    ]
