# Generated by Django 5.1.6 on 2025-03-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0062_pricemovement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceMovement',
            new_name='JumpFall',
        ),
        migrations.RenameIndex(
            model_name='jumpfall',
            new_name='data_analys_symbol_e9b68a_idx',
            old_name='data_analys_symbol_ebd7f1_idx',
        ),
        migrations.RenameIndex(
            model_name='jumpfall',
            new_name='data_analys_date_c663b4_idx',
            old_name='data_analys_date_b5e032_idx',
        ),
        migrations.RenameIndex(
            model_name='jumpfall',
            new_name='data_analys_movemen_e91e35_idx',
            old_name='data_analys_movemen_1fe20c_idx',
        ),
    ]
