# Generated by Django 5.1.6 on 2025-03-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0064_pricevolumecorrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendEffectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('DAY_OF_WEEK', 'Day of Week Returns'), ('WEEKEND_EFFECT', 'Weekend Effect'), ('WEEKLY_STATS', 'Weekly Statistics')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('return_value', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField()),
            ],
        ),
    ]
