# Generated by Django 5.1.6 on 2025-03-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0065_weekendeffectresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousLowVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('consecutive_days', models.PositiveIntegerField(blank=True, null=True)),
                ('max_volume_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Continuous Low Volume Stock',
                'verbose_name_plural': 'Continuous Low Volume Stocks',
                'ordering': ['-consecutive_days', 'symbol'],
            },
        ),
    ]
