# Generated by Django 5.1.6 on 2025-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0066_continuouslowvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighVolumeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, help_text='Actual trading volume on alert day', null=True)),
                ('avg_volume', models.FloatField(blank=True, help_text='Average volume from lookback period', null=True)),
                ('volume_ratio', models.FloatField(blank=True, help_text='Volume to average volume ratio', null=True)),
                ('multiplier_threshold', models.FloatField(blank=True, help_text='Threshold multiplier used', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'High Volume Alert',
                'verbose_name_plural': 'High Volume Alerts',
                'ordering': ['-alert_date', '-volume_ratio'],
            },
        ),
    ]
