# Generated by Django 5.1.6 on 2025-03-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0067_highvolumealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivePriceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('movement_type', models.CharField(blank=True, choices=[('UP', 'Price Increasing'), ('DOWN', 'Price Decreasing')], max_length=4, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_count', models.PositiveIntegerField(blank=True, null=True)),
                ('start_price', models.FloatField(blank=True, null=True)),
                ('end_price', models.FloatField(blank=True, null=True)),
                ('percent_change', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
