# Generated by Django 5.1.6 on 2025-03-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0068_consecutivepricemovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highvolumealert',
            options={},
        ),
    ]
