# Generated by Django 5.1.6 on 2025-03-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0071_alter_pricevolumecorrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jumpfall',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='jumpfall',
            name='data_analys_symbol_e9b68a_idx',
        ),
        migrations.RemoveIndex(
            model_name='jumpfall',
            name='data_analys_date_c663b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='jumpfall',
            name='data_analys_movemen_e91e35_idx',
        ),
    ]
