# Generated by Django 5.1.6 on 2025-03-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0072_alter_jumpfall_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consecutivestreak',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='consecutivestreak',
            name='data_analys_symbol_28a539_idx',
        ),
        migrations.RemoveIndex(
            model_name='consecutivestreak',
            name='data_analys_broker_3e1341_idx',
        ),
        migrations.RemoveIndex(
            model_name='consecutivestreak',
            name='data_analys_streak__634397_idx',
        ),
        migrations.RemoveIndex(
            model_name='consecutivestreak',
            name='data_analys_start_d_84ea75_idx',
        ),
    ]
