# Generated by Django 5.1.6 on 2025-03-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0073_alter_consecutivestreak_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volumetradereport',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='volumetradereport',
            name='data_analys_time_fr_d9dc0e_idx',
        ),
    ]
