# Generated by Django 5.1.6 on 2025-03-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0074_alter_volumetradereport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accumulationdata',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='accumulationdata',
            name='data_analys_symbol_3a1515_idx',
        ),
        migrations.RemoveIndex(
            model_name='accumulationdata',
            name='data_analys_date_1e8101_idx',
        ),
        migrations.RemoveIndex(
            model_name='accumulationdata',
            name='data_analys_time_fr_da426c_idx',
        ),
    ]
