# Generated by Django 5.1.6 on 2025-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0075_alter_accumulationdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuouslowvolume',
            name='avg_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
