# Generated by Django 5.1.6 on 2025-03-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0077_volumespikedetection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccumulationData',
            new_name='Accumulation',
        ),
    ]
