# Generated by Django 5.1.6 on 2025-03-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0078_rename_accumulationdata_accumulation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BulkVolumeTrade',
            new_name='BulkVolume',
        ),
    ]
