# Generated by Django 5.1.6 on 2025-03-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0079_rename_bulkvolumetrade_bulkvolume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsecutivePriceMovement',
            new_name='ConsecutiveUpDown',
        ),
    ]
