# Generated by Django 5.1.6 on 2025-03-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0080_rename_consecutivepricemovement_consecutiveupdown'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IlliquidStockReport',
            new_name='IlliquidStock',
        ),
    ]
