# Generated by Django 5.1.6 on 2025-03-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0081_rename_illiquidstockreport_illiquidstock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JumpFall',
            new_name='JumpFallDetection',
        ),
    ]
