# Generated by Django 5.1.6 on 2025-03-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0082_rename_jumpfall_jumpfalldetection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HighVolumeAlert',
            new_name='SingleDayHighVolume',
        ),
    ]
