# Generated by Django 5.1.6 on 2025-03-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0083_rename_highvolumealert_singledayhighvolume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolumeTradeReport',
            new_name='VolumeTrade',
        ),
    ]
