# Generated by Django 5.1.6 on 2025-03-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0084_rename_volumetradereport_volumetrade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WallBreakTracking',
            new_name='WallBreak',
        ),
    ]
