# Generated by Django 5.1.6 on 2025-03-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0085_rename_wallbreaktracking_wallbreak'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeekendEffectResult',
            new_name='WeekendEffect',
        ),
    ]
