# Generated by Django 5.1.6 on 2025-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0087_brokerpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('selling_broker', models.CharField(blank=True, max_length=20, null=True)),
                ('buying_broker', models.CharField(blank=True, max_length=20, null=True)),
                ('kitta', models.IntegerField(blank=True, null=True)),
                ('first_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(blank=True, null=True)),
                ('days_active', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
