# Generated by Django 5.1.6 on 2025-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0089_consecutivenotrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeDriedUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('avg_volume_past_week', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
