# Generated by Django 5.1.6 on 2025-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0090_volumedriedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayBigTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('total_volume_daily', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date', 'buyer', 'seller')},
            },
        ),
    ]
