# Generated by Django 5.1.6 on 2025-03-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0091_intradaybigtrade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intradaybigtrade',
            unique_together=set(),
        ),
    ]
