# Generated by Django 5.1.6 on 2025-03-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0092_alter_intradaybigtrade_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('price_change_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
