# Generated by Django 5.1.6 on 2025-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0095_alter_tradinghalt_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousVolumeIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('consecutive_days', models.PositiveIntegerField(blank=True, null=True)),
                ('current_volume', models.FloatField(blank=True, null=True)),
                ('percentage_change', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
