# Generated by Django 5.1.6 on 2025-03-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0096_continuousvolumeincrease'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('influence_score', models.FloatField(blank=True, null=True)),
                ('calculation_date', models.DateField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('turnover', models.FloatField(blank=True, null=True)),
                ('price_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['calculation_date', 'rank'],
                'unique_together': {('symbol', 'calculation_date')},
            },
        ),
    ]
