# Generated by Django 5.1.6 on 2025-03-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0097_indexinfluence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexInfluence',
            new_name='BiggestInfluencedStock',
        ),
    ]
