# Generated by Django 5.1.6 on 2025-03-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0098_rename_indexinfluence_biggestinfluencedstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biggestinfluencedstock',
            name='influence_score',
        ),
        migrations.RemoveField(
            model_name='biggestinfluencedstock',
            name='price_change',
        ),
    ]
