# Generated by Django 5.1.6 on 2025-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0099_remove_biggestinfluencedstock_influence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHaltDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('detection_date', models.DateField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('previous_price', models.FloatField(blank=True, null=True)),
                ('pct_change', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=4, null=True)),
                ('turnover', models.FloatField(blank=True, null=True)),
                ('is_circuit', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('symbol', 'detection_date')},
            },
        ),
    ]
