# Generated by Django 5.1.6 on 2025-03-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0100_tradinghaltdetection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradingHalt',
        ),
    ]
