# Generated by Django 5.1.6 on 2025-03-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0101_delete_tradinghalt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiggestInfluencedStock',
        ),
    ]
