# Generated by Django 5.1.6 on 2025-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0102_delete_biggestinfluencedstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiggestInfluencedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('influence_score', models.FloatField(blank=True, null=True)),
                ('calculation_date', models.DateField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
