# Generated by Django 5.1.6 on 2025-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0103_biggestinfluencedstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biggestinfluencedstock',
            options={'ordering': ['calculation_date', 'rank']},
        ),
        migrations.RenameField(
            model_name='biggestinfluencedstock',
            old_name='influence_score',
            new_name='turnover',
        ),
        migrations.AlterField(
            model_name='biggestinfluencedstock',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='biggestinfluencedstock',
            unique_together={('symbol', 'calculation_date')},
        ),
    ]
