# Generated by Django 5.1.6 on 2025-03-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0104_alter_biggestinfluencedstock_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiggestInfluencedStock',
        ),
    ]
