# Generated by Django 5.1.6 on 2025-03-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0105_delete_biggestinfluencedstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.FloatField(blank=True, help_text='Market capitalization in NPR', null=True)),
                ('shares_outstanding', models.FloatField(blank=True, help_text='Total shares outstanding', null=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Metadata',
                'verbose_name_plural': 'Stocks Metadata',
            },
        ),
        migrations.CreateModel(
            name='BiggestInfluencedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('index_influence', models.FloatField(blank=True, help_text="The stock's contribution to index movement in percentage points", null=True)),
                ('calculation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['calculation_date', 'rank'],
                'unique_together': {('symbol', 'calculation_date')},
            },
        ),
    ]
