# Generated by Django 5.1.6 on 2025-03-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0106_stockmetadata_biggestinfluencedstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMetadata',
        ),
    ]
