# Generated by Django 5.1.6 on 2025-03-31 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0108_brokerselftradingreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerselftradingreport',
            name='transaction_no',
        ),
    ]
