# Generated by Django 5.1.6 on 2025-03-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0109_remove_brokerselftradingreport_transaction_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('stock_percentage_change', models.FloatField(blank=True, null=True)),
                ('index_percentage_change', models.FloatField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True)),
                ('is_significant', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
