# Generated by Django 5.1.6 on 2025-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0111_stockreboundreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTradeImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prev_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('impact', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
