# Generated by Django 5.1.6 on 2025-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0112_firsttradeimpact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDominance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('broker', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('buy_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sell_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('self_trade_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_market_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'unique_together': {('symbol', 'date', 'broker')},
            },
        ),
    ]
