# Generated by Django 5.1.6 on 2025-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0114_stock52weekextremes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostTradedSectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'rank'],
                'unique_together': {('date', 'sector')},
            },
        ),
    ]
