# Generated by Django 5.1.6 on 2025-03-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0115_mosttradedsectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowVolatilityStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
        ),
    ]
