# Generated by Django 5.1.6 on 2025-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0116_lowvolatilitystocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeBreakout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('breakout_type', models.CharField(blank=True, choices=[('up', 'Upward Breakout'), ('down', 'Downward Breakout')], max_length=10, null=True)),
                ('breakout_price', models.FloatField(blank=True, null=True)),
                ('reversal_price', models.FloatField(blank=True, null=True)),
                ('resistance', models.FloatField(blank=True, null=True)),
                ('support', models.FloatField(blank=True, null=True)),
                ('breakout_volume', models.FloatField(blank=True, null=True)),
                ('avg_volume', models.FloatField(blank=True, null=True)),
                ('reversal_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'symbol'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
