# Generated by Django 5.1.6 on 2025-03-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0117_fakebreakout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FakeBreakout',
            new_name='StocksFakeBreakout',
        ),
    ]
