# Generated by Django 5.1.6 on 2025-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0118_rename_fakebreakout_stocksfakebreakout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_description', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
