# Generated by Django 5.1.6 on 2025-03-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0119_sectordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostTradedSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('sector_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
