# Generated by Django 5.1.6 on 2025-03-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0121_delete_mosttradedsectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutperformingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_price', models.FloatField(blank=True, null=True)),
                ('stock_change', models.FloatField(blank=True, help_text='Percentage change', null=True)),
                ('index_change', models.FloatField(blank=True, help_text='NEPSE Index percentage change', null=True)),
                ('difference', models.FloatField(blank=True, help_text='Stock change minus index change', null=True)),
                ('stock_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('index_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('outperformance_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-date', '-difference'],
            },
        ),
    ]
