# Generated by Django 5.1.6 on 2025-03-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0122_outperformingstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovementReport',
        ),
    ]
