# Generated by Django 5.1.6 on 2025-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_volume', models.BigIntegerField()),
            ],
        ),
    ]
