# Generated by Django 5.1.6 on 2025-03-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokervolume',
            name='total_volume',
            field=models.FloatField(),
        ),
    ]
