# Generated by Django 5.1.6 on 2025-03-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_brokervolume_total_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_id', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('total_volume', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
