# Generated by Django 5.1.6 on 2025-03-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_aggregatedvolume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AggregatedVolume',
        ),
    ]
