# Generated by Django 5.1.6 on 2025-03-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_delete_aggregatedvolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokervolume',
            name='time_period',
            field=models.CharField(default='latest_date', max_length=50),
        ),
        migrations.AlterField(
            model_name='brokervolume',
            name='broker_id',
            field=models.CharField(max_length=100),
        ),
    ]
