# Generated by Django 5.1.6 on 2025-03-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_brokervolume_time_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('broker_id', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('percent_volume', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
