# Generated by Django 5.1.6 on 2025-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_brokerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerdata',
            name='broker_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='brokerdata',
            name='stock_name',
            field=models.CharField(max_length=10),
        ),
    ]
